version: '3'
services:

  magento2_db:
    build: ./MySql
    container_name: magento2_db
    volumes:
      - magento2_db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento2
      MYSQL_PASSWORD: magento2
    networks:
      - magento2net

  magento2_web:
    build: ./ApachePhp
    container_name: magento2_web
    volumes:
      - ./magento2:/var/www/html
    ports:
      - 80:80
    links:
      - magento2_db:db
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    networks:
      - magento2net

volumes:
  magento2_db_data:
    driver: "local"

networks:
  magento2net:
    driver: "bridge"
